### ISSUE TITLE
Failable 시스템 빠진 부분이 있어요!

### ISSUE THREAD

**Issue by potados99** [inu-appcenter/cafeteria-android#3]
FailbleContainer에서 failables에 하위 FaiableContainer의 모든 failables을 추가해줘야 합니다.

FailableHandler에서 재귀적으로 구현하거나 매번 모든 FailableContainer의 failables을 현재 FailableContainer의 failables에 더해주세요.

**Comment by potados99** [comment]
알겠습니다 곧 처리합니다.

**Comment by doukong** [comment]
???자문자답인가 아수라백작인가

**Comment by potados99** [comment]
페기했습니다 ㅎ
