### ISSUE TITLE
업데이트 후 새 공지 뜰 때

### ISSUE THREAD

**Issue by GHeeJeon** [inu-appcenter/cafeteria-android#33]
투명도 섞는 것보다 아예 불투명으로 가는 건 어떤가여??

**Comment by potados99** [comment]
조하요 감사함니다!!!!!!!!!!!!

**Comment by potados99** [comment]
https://github.com/inu-appcenter/cafeteria-android/commit/3624ca2d1a9030d51f302e205af4d625b00fe67d

끗!
