### ISSUE TITLE
대기번호 등록 아이콘

### ISSUE THREAD

**Issue by GHeeJeon** [inu-appcenter/cafeteria-android#34]
넘모 큐알코드처럼 생겼어요...!
숫자가 아니라 바코드를 찍어야 할 것 같아요
다른 아이콘은 없나여?

**Comment by potados99** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ큐ㅠ 아이콘 찾는데 큐알코드 아이콘이 제일 눈에 띄오서 했어여ㅠㅠ 다른 아이콘 찾아볼게여 ㅎㅎ

**Comment by potados99** [comment]
![image](https://user-images.githubusercontent.com/35878712/103462129-877c3800-4d66-11eb-9efc-efb7042c3fcd.jpeg)

이런느낌으루다 어때여?

**Comment by GHeeJeon** [comment]
> ![image](https://user-images.githubusercontent.com/35878712/103462129-877c3800-4d66-11eb-9efc-efb7042c3fcd.jpeg)
> 
> 이런느낌으루다 어때여?

직관적이예요!! 조아용

**Comment by potados99** [comment]
https://github.com/inu-appcenter/cafeteria-android/commit/dc352acd3ab1a6b20c659ca8c3316690f73fbf69

끗~!
