### ISSUE TITLE
문의 내역 길어지면

### ISSUE THREAD

**Issue by GHeeJeon** [inu-appcenter/cafeteria-android#35]
문의내역이 n줄 이상일 때를 대비해 '더보기' '간략히(또는 접기)' 기능을 추가하면 좋을 것 같아요!

**Comment by potados99** [comment]
옿 그거 해본적 있어여 적용해볼게여 감사함니다~!~!

**Comment by potados99** [comment]
https://github.com/inu-appcenter/cafeteria-android/commit/c3a26ccb027db3385578da991f7b59a953b1b5d3

클리어~~
